---
title: "The World Report"
author: "Us"
date: "April 26, 2019"
output:
  word_document: default
  html_document: default
---

The project...


```{r message=FALSE, warning=FALSE, paged.print=FALSE,dpi=300, fig.width=20,fig.height=11}
#PART 1: Read csv, merge, clean and plot outliers.
library(readr)
library(readxl)
library(dplyr)
library(countrycode)
library(car)

source('Read_Clean.R')
cleaned <- Read_Clean()

#After Cleaning, check how many NA values are in dataset.
# cleaned %>%
#   select(everything()) %>%
#   summarise_all(funs(sum(is.na(.)))) %>% rowSums()
```

```{r}
#PART 2: MDS
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE, dpi=300, fig.width=8,fig.height=8}
# PART 3: PCA
library(pryr)
library(ggbiplot) #if the library is not present use the code below
#library(devtools)
#install_github("vqv/ggbiplot")
source('PCA.R')
(PrinCompPlot <- PCA(cleaned))
```


```{r message=FALSE, warning=FALSE, paged.print=FALSE, dpi=300, fig.width=11,fig.height=7}
# PART 3: Hierarchical Clustering between Continents
library(ape)
source('cluster_continents.R')
Cl_continents <- cluster_continents(cleaned)
```


```{r fig.height=10, fig.width=15, message=FALSE, warning=FALSE, dpi=300}
# PART 4: K-means & Model Based Clustering between Countries
library(mclust)
library(maptools)
source('clusters_countries.R')
Cl_countries <- clusters_countries(cleaned)
#Show Centers
```


```{r}
#PART 5: EFA
```


```{r}
#PART 6: CFA
```

